server.port=${PORT:8080}

# ===========================================
# BASE DE DATOS SUPABASE
# ===========================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# HIKARI (POOL)
# ===========================================

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.auto-commit=false

# ===========================================
# JPA
# ===========================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================================
# JWT
# ===========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===========================================
# LOGS
# ===========================================

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.com.gymlife=DEBUG
logging.level.org.springframework.security=DEBUG

spring.main.banner-mode=off